### ISSUE TITLE
azure api已经配置了，但是右上角语音识别还是提示“未配置Azure语音服务密钥”

### ISSUE THREAD

**Issue by goxofy** [shaonianzhentan/conversation#27]

**Comment by shaonianzhentan** [comment]
已修复

**Comment by goxofy** [comment]
@shaonianzhentan 

大佬，某次版本更新之后，语音识别出现这个问题了

“识别出现异常，请检查Azure语音服务密钥是否正确，或者联系插件作者寻求帮助”

但是实际上已经填入了语音服务密钥

Log如下
```
Error processing audio stream: Only io.IOBase, multidict and (name, file) pairs allowed, use .add_field() for passing more complex parameters, got <function ConversationSttEntity.async_post_audio.<locals>.file_sender at 0x7f62a79277e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 549, in update_body_from_data
    body = payload.PAYLOAD_REGISTRY.get(body, disposition=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/payload.py", line 119, in get
    raise LookupError()
aiohttp.payload.LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/conversation_assistant/stt.py", line 64, in async_process_audio_stream
    text = await self.async_post_audio(stt_stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/conversation_assistant/stt.py", line 79, in async_post_audio
    return await async_speech_recognition(self.speech_key, file_sender)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/conversation_assistant/speech_recognition.py", line 20, in async_speech_recognition
    async with session.post(url, headers=headers, data=buffer_data) as response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 541, in _request
    req = self._request_class(
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 333, in __init__
    self.update_body_from_data(data)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 551, in update_body_from_data
    body = FormData(body)()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/formdata.py", line 37, in __init__
    self.add_fields(*fields)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/formdata.py", line 107, in add_fields
    raise TypeError(
TypeError: Only io.IOBase, multidict and (name, file) pairs allowed, use .add_field() for passing more complex parameters, got <function ConversationSttEntity.async_post_audio.<locals>.file_sender at 0x7f62a79277e0>
```
